### ISSUE TITLE
CRD design

### ISSUE THREAD

**Issue by alexellis** [alexellis/inlets-lb#1]
A CRD can be used to check the status of an inlets tunnel:

For example:

Let's say you created an LB for the echoserver which had traffic on port `8080`:

For internal tracking `inlets-lb` would create the following:

```yaml
metadata:
  name: tunnel-01
kind: inlets-lb
status:
  status: running
  ip: x.x.x.x
  provisionJobPodRef: create-vps-tunnel-01
  clientDeploymentRef: client-tunnel-01
spec:
  host: digitalocean
  region: ams1
  hostSecretRef: digitalocean_access_token
  tunnelAuthTokenRef: server-auth-token-secret-tunnel-01
  port:
   - value: 8080
```

* `host` / `region` correspond to the VPS provider
* `hostSecretRef` is a K8s secret for the token to use with the provider
* `status.provisionJobPodRef` is a job that consumes the above to create the VPS
* `status.ip` is the public IP of the VPS when available
* `status.clientDeploymentRef` is the client-end of the tunnel
* `port` more than one can be specified, but this is the port for the LB

Or it may make sense to break out two CRDs where one represents the Job to provision the VPS and start inlets and one represents the logical tunnel in the cluster including the client Pod.

The user would not interact with this CRD, but the controller would use it for maintaining state and reconciliation.
